# Generated by Django 2.0.7 on 2018-08-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMatterSetting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matters',
            name='EF_StoreId',
            field=models.IntegerField(default=0),
        ),
    ]
