# Generated by Django 2.0.7 on 2018-08-25 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMatterSetting', '0002_matters_ef_storeid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matteralerts',
            old_name='EF_YellowAlert',
            new_name='EF_YellowAmount',
        ),
    ]
