# Generated by Django 2.0.7 on 2018-08-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMatterSetting', '0003_auto_20180825_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubMatterAccessBlocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EF_BlockId', models.IntegerField(default=0)),
                ('EF_StudentId', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='matteraccessblocks',
            name='EF_StudentId',
        ),
    ]
