# Generated by Django 2.0.8 on 2018-10-18 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMatterSetting', '0004_auto_20180825_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matterminremains',
            name='EF_StudentTypeId',
        ),
    ]
