# Generated by Django 2.0.7 on 2018-07-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EF_UserName', models.CharField(max_length=30)),
                ('EF_OfficeAddress', models.TextField()),
                ('EF_PhoneNum', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ChiefColledgeLeaders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EF_TeacherId', models.IntegerField()),
                ('EF_UserName', models.CharField(max_length=30)),
                ('EF_OfficeAddress', models.TextField()),
                ('EF_PhoneNum', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ColledgeLeaders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EF_TeacherId', models.IntegerField()),
                ('EF_UserName', models.CharField(max_length=30)),
                ('EF_OfficeAddress', models.TextField()),
                ('EF_PhoneNum', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Finances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EF_Name', models.CharField(max_length=30)),
                ('EF_TotalAmount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EF_TypeId', models.IntegerField()),
                ('EF_TeacherId', models.IntegerField()),
                ('EF_UserName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StudentTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EF_TypeName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SuperAdministrators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EF_UserName', models.CharField(max_length=30)),
                ('EF_OfficeAddress', models.TextField()),
                ('EF_PhoneNum', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EF_FinancialId', models.IntegerField()),
                ('EF_UserName', models.CharField(max_length=30)),
                ('EF_OfficeAddress', models.TextField()),
                ('EF_PhoneNum', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='UserTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EF_TypeName', models.CharField(max_length=30)),
            ],
        ),
    ]
