# Generated by Django 2.0.7 on 2018-08-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUserManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EF_TypeName', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='administrators',
            name='EF_PassWord',
            field=models.CharField(default='123456', max_length=30),
        ),
        migrations.AddField(
            model_name='administrators',
            name='EF_UserStateId',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='chiefcolledgeleaders',
            name='EF_PassWord',
            field=models.CharField(default='123456', max_length=30),
        ),
        migrations.AddField(
            model_name='chiefcolledgeleaders',
            name='EF_UserStateId',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='colledgeleaders',
            name='EF_PassWord',
            field=models.CharField(default='123456', max_length=30),
        ),
        migrations.AddField(
            model_name='colledgeleaders',
            name='EF_UserStateId',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='students',
            name='EF_PassWord',
            field=models.CharField(default='123456', max_length=30),
        ),
        migrations.AddField(
            model_name='students',
            name='EF_UserStateId',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='superadministrators',
            name='EF_PassWord',
            field=models.CharField(default='123456', max_length=30),
        ),
        migrations.AddField(
            model_name='superadministrators',
            name='EF_UserStateId',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='EF_PassWord',
            field=models.CharField(default='123456', max_length=30),
        ),
        migrations.AddField(
            model_name='teachers',
            name='EF_UserStateId',
            field=models.IntegerField(default='0'),
        ),
    ]
