# Generated by Django 2.0.7 on 2018-08-01 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUserManager', '0002_auto_20180801_1109'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChiefColledgeLeaders',
            new_name='ChiefCollegeLeaders',
        ),
        migrations.RenameModel(
            old_name='ColledgeLeaders',
            new_name='CollegeLeaders',
        ),
        migrations.RenameModel(
            old_name='UserState',
            new_name='UserStates',
        ),
    ]
