# Generated by Django 2.0.7 on 2018-08-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUserManager', '0004_auto_20180801_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrators',
            name='EF_PassWord',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='administrators',
            name='EF_UserName',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='chiefcollegeleaders',
            name='EF_PassWord',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='chiefcollegeleaders',
            name='EF_UserName',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='collegeleaders',
            name='EF_PassWord',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='collegeleaders',
            name='EF_UserName',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='students',
            name='EF_PassWord',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='students',
            name='EF_UserName',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='studenttypes',
            name='EF_TypeName',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='superadministrators',
            name='EF_PassWord',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='superadministrators',
            name='EF_UserName',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='EF_FinancialId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='EF_PassWord',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='EF_UserName',
            field=models.CharField(max_length=30),
        ),
    ]
