# Generated by Django 2.0.7 on 2018-08-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUserManager', '0007_auto_20180819_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrators',
            name='EF_Image',
            field=models.ImageField(default='', upload_to='AdminImage'),
        ),
        migrations.AddField(
            model_name='chiefcollegeleaders',
            name='EF_Image',
            field=models.ImageField(default='', upload_to='ChiefLeaderImage'),
        ),
        migrations.AddField(
            model_name='collegeleaders',
            name='EF_Image',
            field=models.ImageField(default='', upload_to='LeaderImage'),
        ),
        migrations.AddField(
            model_name='students',
            name='EF_Image',
            field=models.ImageField(default='', upload_to='StudentImage'),
        ),
        migrations.AddField(
            model_name='superadministrators',
            name='EF_Image',
            field=models.ImageField(default='', upload_to='SuperAdminImage'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='EF_Image',
            field=models.ImageField(default='', upload_to='TeacherImage'),
        ),
    ]
