# Generated by Django 2.0.7 on 2018-08-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUserManager', '0008_auto_20180819_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrators',
            name='EF_Image',
            field=models.ImageField(default='defalut.png', upload_to='adminImage'),
        ),
        migrations.AlterField(
            model_name='chiefcollegeleaders',
            name='EF_Image',
            field=models.ImageField(default='defalut.png', upload_to='chiefLeaderImage'),
        ),
        migrations.AlterField(
            model_name='collegeleaders',
            name='EF_Image',
            field=models.ImageField(default='defalut.png', upload_to='leaderImage'),
        ),
        migrations.AlterField(
            model_name='students',
            name='EF_Image',
            field=models.ImageField(default='defalut.png', upload_to='studentImage'),
        ),
        migrations.AlterField(
            model_name='superadministrators',
            name='EF_Image',
            field=models.ImageField(default='defalut.png', upload_to='superAdminImage'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='EF_Image',
            field=models.ImageField(default='defalut.png', upload_to='teacherImage'),
        ),
    ]
