# Generated by Django 2.0.7 on 2018-08-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUserManager', '0009_auto_20180819_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrators',
            name='EF_Image',
            field=models.ImageField(default='userImage/adminImage/defalut.png', upload_to='userImage/adminImage'),
        ),
        migrations.AlterField(
            model_name='chiefcollegeleaders',
            name='EF_Image',
            field=models.ImageField(default='userImage/chiefLeaderImage/defalut.png', upload_to='userImage/chiefLeaderImage'),
        ),
        migrations.AlterField(
            model_name='collegeleaders',
            name='EF_Image',
            field=models.ImageField(default='userImage/leaderImage/defalut.png', upload_to='userImage/leaderImage'),
        ),
        migrations.AlterField(
            model_name='students',
            name='EF_Image',
            field=models.ImageField(default='userImage/studentImage/defalut.png', upload_to='userImage/studentImage'),
        ),
        migrations.AlterField(
            model_name='superadministrators',
            name='EF_Image',
            field=models.ImageField(default='userImage/superAdminImage/defalut.png', upload_to='userImage/superAdminImage'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='EF_Image',
            field=models.ImageField(default='userImage/teacherImage/defalut.png', upload_to='userImage/teacherImage'),
        ),
    ]
