# Generated by Django 2.0.7 on 2018-10-21 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUserManager', '0010_auto_20180823_2048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Finances',
        ),
    ]
