# Generated by Django 2.0.7 on 2018-10-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EF_Name', models.CharField(default='', max_length=30)),
                ('EF_TotalAmount', models.FloatField(default=0.0)),
                ('EF_TeacherId', models.IntegerField(default=0)),
            ],
        ),
    ]
