# Generated by Django 2.0.7 on 2018-08-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatterAccessBlocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EF_MatterId', models.IntegerField(default=0)),
                ('EF_StudentTypeId', models.IntegerField(default=0)),
                ('EF_StudentId', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MatterAlerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EF_MatterId', models.IntegerField(default=0)),
                ('EF_YellowAlert', models.IntegerField(default=0)),
                ('EF_RedAmount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MatterMinRemains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EF_MatterId', models.IntegerField(default=0)),
                ('EF_StudentTypeId', models.IntegerField(default=0)),
                ('EF_MinRemain', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Matters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EF_TypeId', models.IntegerField(default=0)),
                ('EF_StateId', models.IntegerField(default=0)),
                ('EF_PurityId', models.IntegerField(default=0)),
                ('EF_UnitId', models.IntegerField(default=0)),
                ('EF_Name', models.CharField(max_length=100)),
                ('EF_CAS', models.CharField(max_length=100)),
                ('EF_Format', models.CharField(max_length=100)),
                ('EF_Amount', models.IntegerField(default=0)),
                ('EF_Price', models.FloatField(default=0.0)),
                ('EF_Location', models.CharField(max_length=100)),
                ('EF_Saler', models.CharField(max_length=30)),
                ('EF_Note', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MatterStates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EF_StateName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MatterTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EF_TypeName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MatterUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EF_UnitName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PurityLevels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EF_LevelName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StoreRooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EF_RoomName', models.CharField(max_length=30)),
            ],
        ),
    ]
