# Generated by Django 2.0.8 on 2018-09-05 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMatterManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='censorestates',
            old_name='EF_States',
            new_name='EF_StateName',
        ),
    ]
