# Generated by Django 2.0.8 on 2018-09-17 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMatterManager', '0002_auto_20180905_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matterdetails',
            old_name='EF_ImportMatterId',
            new_name='EF_ImportFormId',
        ),
    ]
