# Generated by Django 2.0.8 on 2018-10-05 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMatterManager', '0003_auto_20180917_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importforms',
            name='EF_MatterDetailId',
        ),
    ]
