# Generated by Django 2.0.8 on 2018-10-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMatterManager', '0004_remove_importforms_ef_matterdetailid'),
    ]

    operations = [
        migrations.AddField(
            model_name='importforms',
            name='EF_UserTypeId',
            field=models.IntegerField(default=0),
        ),
    ]
