# Generated by Django 2.0.8 on 2018-10-18 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMatterManager', '0005_importforms_ef_usertypeid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportForms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EF_UserTypeId', models.IntegerField(default=0)),
                ('EF_UserId', models.IntegerField(default=0)),
                ('EF_FormStateId', models.IntegerField(default=0)),
                ('EF_Time', models.DateTimeField(default=0)),
                ('EF_CensorePatternId', models.IntegerField(default=0)),
                ('EF_UserId1', models.IntegerField(default=0)),
                ('EF_CensoreStateId1', models.IntegerField(default=0)),
                ('EF_CensoreComment1', models.CharField(default='', max_length=255)),
                ('EF_UserId2', models.IntegerField(default=0)),
                ('EF_CensoreStateId2', models.IntegerField(default=0)),
                ('EF_CensoreComment2', models.CharField(default='', max_length=255)),
                ('EF_UserId3', models.IntegerField(default=0)),
                ('EF_CensoreStateId3', models.IntegerField(default=0)),
                ('EF_CensoreComment3', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ImportMatterDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EF_ImportFormId', models.IntegerField(default=0)),
                ('EF_MatterId', models.IntegerField(default=0)),
                ('EF_MatterCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='MatterDetails',
            new_name='ExportMatterDetails',
        ),
        migrations.RenameField(
            model_name='exportmatterdetails',
            old_name='EF_ImportFormId',
            new_name='EF_ExportFormId',
        ),
    ]
