# Generated by Django 2.0.8 on 2018-10-18 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMatterManager', '0007_preperchaseforms_preperchasematterdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrePerchaseForms',
            new_name='PerchaseForms',
        ),
        migrations.RenameModel(
            old_name='PrePerchaseMatterDetails',
            new_name='PerchaseMatterDetails',
        ),
    ]
